#!/bin/bash

status_code=$(curl --write-out %{http_code} --silent --output /dev/null www.guvi.in)

if [[ "$status_code" -ne 200 ]] ; then
  echo "Site status changed to $status_code" | mail -s "SITE STATUS CHECKER" "psselvas@gmalcom" -r "STATUS_CHECKER"
else
  exit 0
fi
